#ifndef __INTERFACE_H__
#define __INTERFACE_H__

#include <stdint.h>


typedef enum KATSCHA_MODE_ENUM
{
	KATSCHA_MODE_Idle = 0,
	KATSCHA_MODE_Source = 1,
	KATSCHA_MODE_Sink = 2
} KATSCHA_MODE_T;



typedef enum KATSCHA_STATUS_ENUM
{
	KATSCHA_STATUS_Ok = 0,
	KATSCHA_STATUS_InvalidCommand = 1,
	KATSCHA_STATUS_InvalidMode = 2,
	KATSCHA_STATUS_CommandNotPossibleInCurrentMode = 3
} KATSCHA_STATUS_T;



typedef enum KATSCHA_PACKET_TYPE_ENUM
{
	KATSCHA_PACKET_TYPE_COMMAND_Reset = 0,
	KATSCHA_PACKET_TYPE_COMMAND_GetStatus = 1,
	KATSCHA_PACKET_TYPE_COMMAND_SetMode = 2,
	KATSCHA_PACKET_TYPE_COMMAND_GetMode = 3,
	KATSCHA_PACKET_TYPE_COMMAND_SourceSetVoltage = 4,
	KATSCHA_PACKET_TYPE_COMMAND_SourceSetMaxCurrent = 5,
	KATSCHA_PACKET_TYPE_COMMAND_SourceGetVoltage = 6,
	KATSCHA_PACKET_TYPE_COMMAND_SourceGetCurrent = 7,
	KATSCHA_PACKET_TYPE_COMMAND_SinkSetCurrent = 8,
	KATSCHA_PACKET_TYPE_RESPONSE_Status = 9,
	KATSCHA_PACKET_TYPE_RESPONSE_GetStatus = 10,
	KATSCHA_PACKET_TYPE_RESPONSE_GetMode = 11,
	KATSCHA_PACKET_TYPE_RESPONSE_SourceGetVoltage = 12,
	KATSCHA_PACKET_TYPE_RESPONSE_SourceGetCurrent = 13
} KATSCHA_PACKET_TYPE_T;


/* NOTE: Use "pragma pack" instead of "attribute packed" as the latter does not work on MinGW.
 *       See here for details: https://sourceforge.net/p/mingw-w64/bugs/588/
 */
#pragma pack(push, 1)

typedef struct KATSCHA_PACKET_HEADER_STRUCT
{
	uint8_t  ucPacketType;
} KATSCHA_PACKET_HEADER_T;

typedef struct KATSCHA_PACKET_COMMAND_RESET_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
} KATSCHA_PACKET_COMMAND_RESET_T;

typedef struct KATSCHA_PACKET_COMMAND_GET_STATUS_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
} KATSCHA_PACKET_COMMAND_GET_STATUS_T;

typedef struct KATSCHA_PACKET_COMMAND_SET_MODE_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint8_t ucMode;
} KATSCHA_PACKET_COMMAND_SET_MODE_T;

typedef struct KATSCHA_PACKET_COMMAND_GET_MODE_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
} KATSCHA_PACKET_COMMAND_GET_MODE_T;

typedef struct KATSCHA_PACKET_COMMAND_SOURCE_SET_VOLTAGE_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint32_t ulPwmValue;
} KATSCHA_PACKET_COMMAND_SOURCE_SET_VOLTAGE_T;

typedef struct KATSCHA_PACKET_COMMAND_SOURCE_SET_MAX_CURRENT_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint32_t ulMaxCurent;
} KATSCHA_PACKET_COMMAND_SOURCE_SET_MAX_CURRENT_T;

typedef struct KATSCHA_PACKET_COMMAND_SOURCE_GET_VOLTAGE_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
} KATSCHA_PACKET_COMMAND_SOURCE_GET_VOLTAGE_T;

typedef struct KATSCHA_PACKET_COMMAND_SOURCE_GET_CURRENT_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
} KATSCHA_PACKET_COMMAND_SOURCE_GET_CURRENT_T;

typedef struct KATSCHA_PACKET_COMMAND_SINK_SET_CURRENT_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint32_t ulCurent;
} KATSCHA_PACKET_COMMAND_SINK_SET_CURRENT_T;

typedef struct KATSCHA_PACKET_RESPONSE_STATUS_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint8_t ucStatus;
} KATSCHA_PACKET_RESPONSE_STATUS_T;

typedef struct KATSCHA_PACKET_RESPONSE_GET_STATUS_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint8_t ucStatus;
	uint8_t ucMode;
	uint32_t ulSourceVoltage;
	uint32_t ulSourceCurrent;
	uint32_t ulSinkCurrent;
	uint32_t ulPwmValue;
	uint32_t ulRdacValue;
	uint32_t ulDacCurrentSink;
} KATSCHA_PACKET_RESPONSE_GET_STATUS_T;

typedef struct KATSCHA_PACKET_RESPONSE_GET_MODE_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint8_t ucStatus;
	uint8_t ucMode;
} KATSCHA_PACKET_RESPONSE_GET_MODE_T;

typedef struct KATSCHA_PACKET_RESPONSE_SOURCE_GET_VOLTAGE_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint8_t ucStatus;
	uint32_t ulVoltage;
} KATSCHA_PACKET_RESPONSE_SOURCE_GET_VOLTAGE_T;

typedef struct KATSCHA_PACKET_RESPONSE_SOURCE_GET_CURRENT_STRUCT
{
	KATSCHA_PACKET_HEADER_T tHeader;
	uint8_t ucStatus;
	uint32_t ulCurrent;
} KATSCHA_PACKET_RESPONSE_SOURCE_GET_CURRENT_T;


#pragma pack(pop)

typedef union KATSCHA_PACKET_UNION
{
	unsigned char auc[64];
	KATSCHA_PACKET_HEADER_T tHeader;
	KATSCHA_PACKET_COMMAND_RESET_T tCommandReset;
	KATSCHA_PACKET_COMMAND_GET_STATUS_T tCommandGetStatus;
	KATSCHA_PACKET_COMMAND_SET_MODE_T tCommandSetMode;
	KATSCHA_PACKET_COMMAND_GET_MODE_T tCommandGetMode;
	KATSCHA_PACKET_COMMAND_SOURCE_SET_VOLTAGE_T tCommandSourceSetVoltage;
	KATSCHA_PACKET_COMMAND_SOURCE_SET_MAX_CURRENT_T tCommandSourceSetMaxCurrent;
	KATSCHA_PACKET_COMMAND_SOURCE_GET_VOLTAGE_T tCommandSourceGetVoltage;
	KATSCHA_PACKET_COMMAND_SOURCE_GET_CURRENT_T tCommandSourceGetCurrent;
	KATSCHA_PACKET_COMMAND_SINK_SET_CURRENT_T tCommandSinkSetCurrent;
	KATSCHA_PACKET_RESPONSE_STATUS_T tResponseStatus;
	KATSCHA_PACKET_RESPONSE_GET_STATUS_T tResponseGetStatus;
	KATSCHA_PACKET_RESPONSE_GET_MODE_T tResponseGetMode;
	KATSCHA_PACKET_RESPONSE_SOURCE_GET_VOLTAGE_T tResponseGetVoltage;
	KATSCHA_PACKET_RESPONSE_SOURCE_GET_CURRENT_T tResponseGetCurrent;
} KATSCHA_PACKET_T;

#endif  /* __INTERFACE_H__ */
